baseURL = 'http://raphgl.com/'
languageCode = 'en-us'
title = 'RaphGL'
publishDir = 'docs'
pluralizelisttitles = 'false'
summaryLength = 20

[markup]
[markup.highlight]
style = "dracula"
tabwidth = 4
codeFences = true
noClasses = false

[taxonomies]
tag = "tags"
